### ISSUE TITLE
fail_below_threshold is not working correctly 

### ISSUE THREAD

**Issue by PhilippPelchmann** [PavanMudigonda/jacoco-reporter#1]
**Describe the bug**
Fail below threshold is not working as expected - step fails, even if the threshold is below the code coverage for version 2.3

**Additional context**
The fix is in `action.ps1` the variable `coverage_value` already holds the correct coverage percentage.

current version:
```
if ($coverage_value.coveragePercentage -lt $inputs.minimum_coverage -and $inputs.fail_below_threshold -eq "true") {
        $script:stepShouldFail = $true
    }
```

correct:  

```
if ($coverage_value -lt $inputs.minimum_coverage -and $inputs.fail_below_threshold -eq "true") {
        $script:stepShouldFail = $true
    }
```

**Comment by markus-arndt-senacor** [comment]
Same issue here

**Comment by PavanMudigonda** [comment]
Will fix it. Thanks for reporting

**Comment by PavanMudigonda** [comment]
@markus-arndt-senacor @PhilippPelchmann  Please hit the star icon at top if you liked my GH Action. Appreciate your support in reporting and fixing issue.

**Comment by PhilippPelchmann** [comment]
@PavanMudigonda  thank you for the fixing it so quickly - working as expected now!
