### ISSUE TITLE
Should consider checking when $coveredLines is 0

### ISSUE THREAD

**Issue by chenggangpro** [PavanMudigonda/jacoco-reporter#19]
Hi guys,

  I'm new here.It seems like a bug as I mentioned below . When `$coveredLines` is 0, there is no place to check "$coveredLines" .  Then it will raise an error about `Attempted to divide by zero.`
  I think when `$coveredLines` is 0  , `$coveragePercentage` should be zero directly

https://github.com/PavanMudigonda/jacoco-reporter/blob/95a0b976e99043d65782a3a68f3fda0b51dbd5f6/action.ps1#L142

**Comment by PavanMudigondaTR** [comment]
@chenggangpro 

Thanks for reporting. I have fixed it today and it should work for you 

if ($missedLines -eq 0 -or $coveredLines -eq 0) 
    {
    $coveragePercentage = 100
    } 
else 
    {
    $coveragePercentage = [math]::Round(100 - (($missedLines / $coveredLines) * 100))
    }

**Comment by PavanMudigonda** [comment]
@chenggangpro 

If the fix is working for you hit  STAR ⭐ on top right of this repo
