### ISSUE TITLE
Cannot bind coveragePercentageString argument to parameter 'Value' in actions.ps1:244

### ISSUE THREAD

**Issue by jaroslaw-drapala-gss** [PavanMudigonda/jacoco-reporter#23]
**Describe the bug**
Cannot bind coveragePercentageString argument to parameter 'Value' in actions.ps1:244 because it is an empty string
[https://github.com/PavanMudigonda/jacoco-reporter/blob/main/action.ps1#L244](url)

**To Reproduce**
1. Run 'JaCoCo Code Coverage Report'
2. If one of the condition is true then coveragePercentageString is never set
[https://github.com/PavanMudigonda/jacoco-reporter/blob/main/action.ps1#L222](url)
4. Error: Cannot bind argument to parameter 'Value' because it is an empty string.

**Expected behavior**
coveragePercentageString shouldn't be an empty string

**Screenshot**
![image](https://user-images.githubusercontent.com/107402729/180158977-900abdfc-45da-4646-ada4-175159b17f67.png)

**Comment by PavanMudigondaTR** [comment]
@jaroslaw-drapala-gss i will fix it today!

**Comment by PavanMudigonda** [comment]
@jaroslaw-drapala-gss I have fixed in v4.6 
Could you please try again by updating version number ?

**Comment by jaroslaw-drapala-gss** [comment]
@PavanMudigonda 
Seems to be working fine now. thx.
