### ISSUE TITLE
Display Coverage Percent along with Check

### ISSUE THREAD

**Issue by SatheeshJM** [PavanMudigonda/jacoco-reporter#26]
**Is your feature request related to a problem? Please describe.**
There is no way to know just coverage percentage in the pull request page. One has to go inside the job to find out coverage. 

**Describe the solution you'd like**
If the check contains coverage percent, it would be super useful. 
The attached screenshot contains a Junit Report summary.   Something similar containing coverage percentage would be super useful. 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1222562/195974012-0f2efd25-326d-432b-9176-710f34940166.png">

**Comment by PavanMudigondaTR** [comment]
@SatheeshJM  Hi Satheesh, Thanks for your input. I will check if i can add it quickly today !

**Comment by PavanMudigondaTR** [comment]
> **Is your feature request related to a problem? Please describe.** There is no way to know just coverage percentage in the pull request page. One has to go inside the job to find out coverage.
> 
> **Describe the solution you'd like** If the check contains coverage percent, it would be super useful. The attached screenshot contains a Junit Report summary. Something similar containing coverage percentage would be super useful.
> 
> <img alt="image" width="1049" src="https://user-images.githubusercontent.com/1222562/195974012-0f2efd25-326d-432b-9176-710f34940166.png">

Could you please send me link to the Junit Repot Action you are referrring to so i can understand better !

**Comment by SatheeshJM** [comment]
@PavanMudigondaTR 
Thank you for the quick response! 

This is the Github Action I'm using - https://github.com/mikepenz/action-junit-report

This is my current setup 
<img width="548" alt="image" src="https://user-images.githubusercontent.com/1222562/196023689-00ea8a15-86ad-43a1-9774-0d0e07597db9.png">


I was digging a bit into their code base, I believe the update happens at 
https://github.com/mikepenz/action-junit-report/blob/ab07dd7abefd456d92ecbeb22f81392fafe3d528/src/annotator.ts#L65

**Comment by PavanMudigondaTR** [comment]
@SatheeshJM  I am working on implementing this ! I will let you know once done. sorry for the delay to get to this !

**Comment by SatheeshJM** [comment]
@PavanMudigondaTR no issues! 
I came up with a hacky working solution for our use.. 

here is the link if it helps - https://github.com/SatheeshJM/jacoco-reporter/releases/tag/v4.6_jm_patch_4

(diff can be found here - https://github.com/SatheeshJM/jacoco-reporter/compare/7194fecaeda54ed9f8b08a4efbbfbf4c1b5bb027..v4.6_jm_patch_4 )

**Comment by PavanMudigondaTR** [comment]
@SatheeshJM  Please let me know if, if this is sufficient enough ?

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/86745613/206934926-9fb93523-f051-4dd1-bca8-9eda68c81554.png">

**Comment by SatheeshJM** [comment]
This seems pretty good! Thank you @PavanMudigondaTR

**Comment by PavanMudigonda** [comment]
@SatheeshJM  

I have implemented this in v4.8. Please try.
