### ISSUE TITLE
Invalid format '# Coverage Report: Test coverage results'

### ISSUE THREAD

**Issue by oleksiiRybak** [PavanMudigonda/jacoco-reporter#27]
**Describe the bug**
The job fails with the message:
Error: Unable to process file command 'output' successfully.
Error: Invalid format '# Coverage Report: Test coverage results'. 

It used to work before but now it fails and not sure where the problem is. 

**To Reproduce**
1. Go to https://github.com/AnswerConsulting/AnswerKing-Java/actions/runs/3446304463/jobs/5751041279
2. Re-run the job and see the error.
3. Scroll down to 'Publish test coverage results' step. 

**Expected behavior**
I shouldn't fail with the output thing as it didn't complain about it before. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12736698/201382374-8a507fa0-8768-47d6-836f-99462e2e0aeb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version

**Comment by PavanMudigondaTR** [comment]
Working on fixing it. got this reported by my team mates as well !

**Comment by PavanMudigondaTR** [comment]
@oleksiiRybak  Fixed. Simply try rerunning and see if it works !

**Comment by PavanMudigondaTR** [comment]
Fix working as per team members from my Org. I would prefer to close issue !

**Comment by oleksiiRybak** [comment]
Hi Pavan, 
thank you for your help and providing the fix, much appreciated. It works OK now.
