### ISSUE TITLE
Deprecation warning from github

### ISSUE THREAD

**Issue by chrissearle** [PavanMudigonda/jacoco-reporter#31]
The reporter is working fine but on completed run this gets added to the action run summary:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: PavanMudigonda/jacoco-reporter@v4.7

**Comment by PavanMudigondaTR** [comment]
fixed in v4.7
