### ISSUE TITLE
Code coverage differs from JaCoCo report

### ISSUE THREAD

**Issue by opwvhk** [PavanMudigonda/jacoco-reporter#43]
**Describe the bug**

The code coverage as added to the workflow differs from what JaCoCo reports.

**To Reproduce**

Steps to reproduce the behaviour:
1. Add the action to a Java project with interfaces and/or classes that are excluded
2. Let the workflow run
3. See the result, e.g.: https://github.com/opwvhk/avro-conversions/actions/runs/5077740253/jobs/9121402487

What we see here is that interfaces, like `SimpleContentHandler.java`, don't have any details.

Also, excluded classes like `FixedXmlSchemaWalker.java` mark many lines as missed, whereas this class should not be in the report at all!

**Expected behaviour**

* The coverage report does not include excluded classes.
* The coverage report does not mark interfaces with a cross.

**Comment by PavanMudigondaTR** [comment]
@opwvhk 

It appears to be problem with https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin

Also I suggest you try to verify syntax of "exclude" in pom.xml 

![image](https://github.com/PavanMudigonda/jacoco-reporter/assets/86745613/70ed09b2-fc5f-47c2-9178-ac1a7c1fb629)


![image](https://github.com/PavanMudigonda/jacoco-reporter/assets/86745613/817ae05e-8ef9-4e5b-91a9-e6b4a465128d)

**Comment by opwvhk** [comment]
Thank you; that triggered a change that fixed most of it. Now, I only get crosses for classes without code (pure interfaces). Good enough.
