### ISSUE TITLE
Previous Bump of Node 16 to 20 not working

### ISSUE THREAD

**Issue by Ponnia-M** [PavanMudigonda/jacoco-reporter#62]
Error message in our github action workflow run: `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: PavanMudigonda/jacoco-reporter@v4.9`

**Comment by gustavotiengo** [comment]
@Ponnia-M I believe next release will cover the node update requirement.
@PavanMudigonda already upgraded node version with this commit: https://github.com/PavanMudigonda/jacoco-reporter/commit/4fc6bf270fe893e8dda5467e432253a6961345b8

**Comment by Ponnia-M** [comment]
Thanks for the update, but this error still persist after I updated my workflow with `PavanMudigonda/jacoco-reporter@v4.9`. Will be on the look out for this update.

**Comment by PavanMudigondaTR** [comment]
@Ponnia-M  Hi, i will make new release tomorrow with node20. thanks !

**Comment by Ponnia-M** [comment]
Hey just following up about the progress on this release

**Comment by gustavotiengo** [comment]
@Ponnia-M It's already available!
You just need to replace 4.9 with 5.0 in your Actions workflow 

Thank you @PavanMudigondaTR
Keep doing this amazing job =)

**Comment by PavanMudigonda** [comment]
Thank you @gustavotiengo @Ponnia-M 

v5.0 should fix this deprecation prompt. Let me know if it doesn't work
