### ISSUE TITLE
403 on GH API check-runs from PR

### ISSUE THREAD

**Issue by ascheman** [PavanMudigonda/jacoco-reporter#68]
**Describe the bug**

I do get the following error [on a GH Action run for a PR](https://github.com/aim42/htmlSanityCheck/actions/runs/11293820921/job/31442760324). 
I am not even sure whether it is a software bug. 
Perhaps I didn't set write token/permissions (in this case please try to clarify).
This is just an excerpt of the output, I could provide more details if necessary.

```
VERBOSE: Resolving XML file relative to current directory: /home/runner/work/htmlSanityCheck/htmlSanityCheck/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
VERBOSE: Resolving default XSL file: /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v5.0/jacoco-report/jacocoxml2md.xsl
VERBOSE: Loaded XSL transformer
VERBOSE: Transforming XML to MD
Covered Lines: 1048
Missed Lines: 85
Total Lines: 1133
Coverage: 92.5
Publishing Report to GH Workflow

Resolving REF

Resolving PR REF

Resolved REF as 14f03607eab89da5901a7246b92fe98da05a9671

Resolve Repo Full Name as aim42/htmlSanityCheck

Adding Check Run

System.Collections.Hashtable

https://api.github.com/repos/aim42/htmlSanityCheck/check-runs

System.Collections.Hashtable

Invoke-WebRequest: /home/runner/work/_actions/PavanMudigonda/jacoco-reporter/v5.0/action.ps1:338
Line |
 338 |      Invoke-WebRequest -Headers $hdr $url -Method Post -Body ($bdy | C …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  {   "message": "Resource not accessible by integration",  
     | "documentation_url":
     | "https://docs.github.com/rest/checks/runs#create-a-check-run",  
     | "status": "[40](https://github.com/aim42/htmlSanityCheck/actions/runs/11293820921/job/31442760324#step:5:41)3" }
Error: The process '/usr/bin/pwsh' failed with exit code 1
```

**To Reproduce**
Not sure how to reproduce the problem (of course, I can re-run the GH Action). But from the outside? Perhaps create a new PR against my repo (see above)?

**Expected behavior**
Test report should be published to GH Action run.

**Additional context**
Error is raised in [this GH Action](https://github.com/aim42/htmlSanityCheck/blob/506bd9c06e25baf31f1c5ca8842fc1e8157c66ef/.github/workflows/gradle-build.yml#L35)

**Comment by ascheman** [comment]
Sorry, I see this a [known problem](https://github.com/PavanMudigonda/jacoco-reporter#important-notes-)

**Comment by ascheman** [comment]
I followed the recommended action by adding a `permissions` block to the GH action workflow.
However, I still run into the problem. 

Would you mind having a look into my configuration, @PavanMudigonda ? 
https://github.com/aim42/htmlSanityCheck/blob/ed0e1a322e539d61fdb1a5db59547eeed9e63bd3/.github/workflows/gradle-build.yml#L1

**Comment by PavanMudigondaTR** [comment]
@ascheman  i am checking this.

**Comment by PavanMudigondaTR** [comment]
I was not able to figure what caused this but this certainly due to permissions issue. Can you provide a PAT token instead of the default token and this will resolve this easily as work around ?

github_token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}

**Comment by ascheman** [comment]
Thanks for your support @PavanMudigondaTR - I think I found the problem (running everything with debug mode enabled).
Looks like there is a very similar behaviour in the GH action I run directly before yours (cf. https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions).
